### ISSUE TITLE
Installer for Windows

### ISSUE THREAD

**Issue by nblackburn** [msipos/syntaxic#18]
A installer for windows would be nice and recommend NSIS as the best solution for this.

**Comment by msipos** [comment]
Thanks, @nblackburn .

I just went through the process of making an MSI installer with Wix.  I decided on it over NSIS, mostly because it .MSI installers seem more modern to me.  Also, MSI allows easy upgrades, something I read is difficult to do with NSIS.

That said, Wix was very hard to get working.  The documentation is horrible and tutorials are pretty bad.  I'll write a blog post about the script I used to build the MSI package.

I've uploaded the installer [here](https://syntaxiceditor.com/#download).  However, I'd be curious to hear why you prefer NSIS?

**Comment by nblackburn** [comment]
Easy to learn and very flexible but so is Wix once you understand how windows installer works. I didn't think about Wix at the time of writing.
