### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by corelon** [msipos/syntaxic#31]
Hello,

I tried contacting you through email and twitter but I got no answer (hopefully here it will not be the case). What is the current status of the project? Is it progressing? Is there any release coming soon?

Many thanks

**Comment by jahio** [comment]
I have this exact same question. Haven't seen any updates since May/June this year, and while the feature set _alone_ has me quite interested, I'm hesitant to buy if the project's been abandoned or even put on the back burner. Can you please let us know what's happening with this project? **Is it dead?**

**Comment by msipos** [comment]
Hi @corelon and @jaustinhughey ,

Glad to see you interested!

Since I started working on Syntaxic, some more interesting (and much more major) products have come out, e.g. Atom and Visual Studio Code.  So, for the time being this product is dead.

It is actually on my to-do list this holiday to **fully open source it**.  I hope to get this done in the next 2 weeks.

Thanks for your interest.

**Comment by jahio** [comment]
Hey there @msipos, just wanted to pop in here real quick and say thank you very much for responding and doing so in such a straightforward, no-bs manner. I definitely think open sourcing it is a great idea. My biggest reason for wanting to see Syntaxic continue, get improved, etc. is that it's the first editor I've seen that seems to have a _decent_ built-in terminal. You'd think something like that would be relatively simple, and you can get all kinds of editors with javascript consoles, but when you really just want a terminal inside your editor (no matter the reason), it seems like - at least on OS X - we're pretty much screwed.

Anyway, thank you again for letting us know what's up, and for being forward-thinking enough to open source the application itself. I'm sure I'm not the only one out there who appreciates it! Have a great christmahaunakwanza and a fantastic New Year's :)
